console.log('João nasceu em 1984.')
console.log('Em 2000 João conheceu Maria.')
console.log('João casou-se com Maria em 2012.')
console.log('Maria teve 1 filho com João em 2015.')
console.log('O filho de João se chama Eduardo.')
